#!/usr/bin/env bash
#
# env-auth.sh — Auth PoC configuration + JWT helpers
#
# Source AFTER shared/env.sh + helpers.sh:
#   source "${SCRIPT_DIR}/env-auth.sh"
#
# Implements the PoC from docs/auth/jwt-enforcement-design.md §10.
#

# --- Cloud Run services ---
AUTH_ECHO_SERVICE="cr-auth-echo"
IDP_MOCK_SERVICE="cr-idp-mock"

# --- Container images (same AR repo as shared) ---
AUTH_ECHO_IMAGE_URL="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/auth-echo:latest"
IDP_MOCK_IMAGE_URL="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/idp-mock:latest"

# --- Apigee ---
AUTH_PROXY_NAME="cr-auth-jwt"          # proxy with BasePath /auth-echo
AUTH_SHAREDFLOW="auth-verify"          # VerifyJWT shared flow, attached via flow hook
# Hook ID casing matters: the API accepts only PreProxyFlowHook /
# PreTargetFlowHook / PostTargetFlowHook / PostProxyFlowHook (capital H —
# "PreProxyFlowhook" is rejected with INVALID_ARGUMENT, found live).
AUTH_FLOWHOOK="PreProxyFlowHook"       # env-level hook — applies to ALL proxies in the env

# --- Token model (docs/auth/jwt-enforcement-design.md §2) ---
# Client JWT (the in-house issuer's token):
JWT_ISSUER="https://idp.poc.internal"
JWT_AUDIENCE="api://apigee-poc"        # client JWT aud — checked by VerifyJWT + middleware
JWT_KID="poc-key-1"
# Google ID token (the hop identity) uses a Cloud Run CUSTOM audience — a
# fixed string instead of the per-service URL (§10 item 5):
GOOGLE_CUSTOM_AUDIENCE="apigee-poc-auth"

# --- Envoy sidecar variant (§10 item 6) — deployed by setup.sh alongside
# the library variant, as peers. Multi-container service: Envoy jwt_authn
# ingress container in front of the same echo app (middleware off). Envoy
# gets the JWKS inline via env — the §7.4 finding rules out a run→run fetch
# of the internal-ingress mock IdP.
AUTH_ECHO_ENVOY_SERVICE="cr-auth-echo-envoy"
ENVOY_IMAGE_URL="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/auth-envoy:latest"
AUTH_ENVOY_PROXY_NAME="cr-auth-jwt-envoy"  # proxy with BasePath /auth-echo-envoy
ENVOY_APP_PORT="8081"                      # app container behind Envoy (PORT=8080 is Envoy's)

# --- Local state (RSA keypair standing in for the external issuer's keys) ---
# Gitignored — regenerated by setup.sh if absent.
AUTH_STATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/state"
AUTH_PRIVATE_KEY="${AUTH_STATE_DIR}/idp-private.pem"

# base64url encode stdin (no padding)
b64url() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
}

# Build the JWKS JSON for the current keypair (public material only).
# Modulus via openssl, exponent 65537 = AQAB.
build_jwks_json() {
  local modulus_hex
  modulus_hex="$(openssl rsa -in "${AUTH_PRIVATE_KEY}" -noout -modulus | cut -d= -f2)"
  local n_b64
  n_b64="$(python3 -c "
import base64, binascii, sys
print(base64.urlsafe_b64encode(binascii.unhexlify(sys.argv[1])).rstrip(b'=').decode())
" "${modulus_hex}")"
  printf '{"keys":[{"kty":"RSA","alg":"RS256","use":"sig","kid":"%s","n":"%s","e":"AQAB"}]}' \
    "${JWT_KID}" "${n_b64}"
}

# Mint an RS256 JWT signed with the PoC private key.
# Usage: mint_jwt <iss> <aud> <exp-offset-seconds> [sub] [scope]
# (negative offset mints an already-expired token)
mint_jwt() {
  local iss="$1" aud="$2" exp_offset="$3" sub="${4:-test-user}" scope="${5:-echo.read}"
  local now exp header payload sig
  now="$(date +%s)"
  exp=$((now + exp_offset))
  header="$(printf '{"alg":"RS256","typ":"JWT","kid":"%s"}' "${JWT_KID}" | b64url)"
  payload="$(printf '{"iss":"%s","aud":"%s","sub":"%s","scope":"%s","iat":%d,"exp":%d}' \
    "${iss}" "${aud}" "${sub}" "${scope}" "${now}" "${exp}" | b64url)"
  sig="$(printf '%s.%s' "${header}" "${payload}" \
    | openssl dgst -sha256 -sign "${AUTH_PRIVATE_KEY}" -binary | b64url)"
  printf '%s.%s.%s' "${header}" "${payload}" "${sig}"
}

# Resolve the Apigee runtime instance IP (empty if Apigee absent).
apigee_instance_ip() {
  curl -s -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    "${APIGEE_API}/organizations/${PROJECT_ID}/instances/${INSTANCE_NAME}" 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('host',''))" 2>/dev/null || true
}
